# Generated by Django 5.0 on 2023-12-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hududiy_raqam', models.IntegerField()),
                ('Nomer', models.CharField(max_length=6)),
                ('Boshlanish_sanasi', models.DateField()),
                ('Boshlanish_narxi', models.IntegerField()),
                ('Malumot', models.TextField()),
            ],
        ),
    ]
